<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.310">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Open Geomatics Community of Practice - 3&nbsp; Exercise 2: VRI Forest Cover and Digital Imagery</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Course Data Description.html" rel="next">
<link href="./01-Introduction to Forestry Datasets in QGIS.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./02-VRI Forest Cover and Digital Imagery.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Exercise 2: VRI Forest Cover and Digital Imagery</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Open Geomatics Community of Practice</a> 
        <div class="sidebar-tools-main">
    <div class="dropdown">
      <a href="" title="Download" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" aria-label="Download"><i class="bi bi-download"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="./Open-Geomatics-Community-of-Practice.pdf">
              <i class="bi bi-bi-file-pdf pe-1"></i>
            Download PDF
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="./Open-Geomatics-Community-of-Practice.epub">
              <i class="bi bi-bi-journal pe-1"></i>
            Download ePub
            </a>
          </li>
      </ul>
    </div>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">FRST 556: Land Information Acquisition and Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-Introduction to Forestry Datasets in QGIS.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introduction to Forestry Datasets in QGIS</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-VRI Forest Cover and Digital Imagery.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Exercise 2: VRI Forest Cover and Digital Imagery</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Course Data Description.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Data Description for FRST 556 course data</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#lab-overview" id="toc-lab-overview" class="nav-link active" data-scroll-target="#lab-overview">Lab Overview</a></li>
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link" data-scroll-target="#learning-objectives">Learning Objectives</a></li>
  <li><a href="#task-1-discover-the-difference-between-forest-cover-and-vri" id="toc-task-1-discover-the-difference-between-forest-cover-and-vri" class="nav-link" data-scroll-target="#task-1-discover-the-difference-between-forest-cover-and-vri">Task 1: Discover the difference between “Forest Cover” and VRI</a>
  <ul class="collapse">
  <li><a href="#question-1" id="toc-question-1" class="nav-link" data-scroll-target="#question-1"><span class="header-section-number">3.0.1</span> Question 1:</a></li>
  <li><a href="#question-2" id="toc-question-2" class="nav-link" data-scroll-target="#question-2"><span class="header-section-number">3.0.2</span> Question 2:</a></li>
  <li><a href="#question-3" id="toc-question-3" class="nav-link" data-scroll-target="#question-3"><span class="header-section-number">3.0.3</span> Question 3:</a></li>
  <li><a href="#question-4" id="toc-question-4" class="nav-link" data-scroll-target="#question-4"><span class="header-section-number">3.0.4</span> Question 4:</a></li>
  <li><a href="#question-5" id="toc-question-5" class="nav-link" data-scroll-target="#question-5"><span class="header-section-number">3.0.5</span> Question 5:</a></li>
  </ul></li>
  <li><a href="#task-2-segmenting-forest-polygons" id="toc-task-2-segmenting-forest-polygons" class="nav-link" data-scroll-target="#task-2-segmenting-forest-polygons">Task 2: Segmenting Forest Polygons</a>
  <ul class="collapse">
  <li><a href="#sec-Q6" id="toc-sec-Q6" class="nav-link" data-scroll-target="#sec-Q6">Question 6:</a></li>
  <li><a href="#question-7" id="toc-question-7" class="nav-link" data-scroll-target="#question-7">Question 7:</a></li>
  <li><a href="#question-8" id="toc-question-8" class="nav-link" data-scroll-target="#question-8">Question 8:</a></li>
  </ul></li>
  <li><a href="#task-3-understand-variability-in-pixel-data" id="toc-task-3-understand-variability-in-pixel-data" class="nav-link" data-scroll-target="#task-3-understand-variability-in-pixel-data">Task 3: Understand Variability in Pixel Data</a>
  <ul class="collapse">
  <li><a href="#question-9" id="toc-question-9" class="nav-link" data-scroll-target="#question-9">Question 9:</a></li>
  <li><a href="#question-10" id="toc-question-10" class="nav-link" data-scroll-target="#question-10">Question 10:</a></li>
  <li><a href="#map-1" id="toc-map-1" class="nav-link" data-scroll-target="#map-1">Map 1:</a></li>
  </ul></li>
  <li><a href="#task-4-satellite-images-compared-to-aerial-photographs" id="toc-task-4-satellite-images-compared-to-aerial-photographs" class="nav-link" data-scroll-target="#task-4-satellite-images-compared-to-aerial-photographs">Task 4: Satellite Images Compared to Aerial Photographs</a>
  <ul class="collapse">
  <li><a href="#question-11" id="toc-question-11" class="nav-link" data-scroll-target="#question-11">Question 11:</a></li>
  <li><a href="#question-12" id="toc-question-12" class="nav-link" data-scroll-target="#question-12">Question 12:</a></li>
  </ul></li>
  <li><a href="#lab-questions-deliverables" id="toc-lab-questions-deliverables" class="nav-link" data-scroll-target="#lab-questions-deliverables">Lab Questions &amp; Deliverables</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="terrain-spatial-interpolation" class="quarto-section-identifier"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Exercise 2: VRI Forest Cover and Digital Imagery</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning in readLines(file, warn = readLines.warn): incomplete final line found
on 'chapterauthors.yml'</code></pre>
</div>
</div>
<p>Written by</p>
<p>Sarah Smith-Tripp</p>
<section id="lab-overview" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="lab-overview">Lab Overview</h2>
<p>British Columbia relies heavily on surveying from aerial imagery to understand forest health. Aerial surveys have been used throughout BC’s recent history to understand forest composition and health. Aerial imagery is the key input into the vegetation resource inventory (or VRI) used to understand the composition of BCs forests. The process has two phases:</p>
<ul>
<li><p>Phase 1: Using aerial imagery, forests are divided into homogeneous areas called “polygons.”</p></li>
<li><p>Phase 2: Ground-reference plots are placed systematically throughout polygons. Ground-reference plots are used to determine the site-type or biogeoclimatic zone and subzone of each area. You can find more information on this process <a href="https://cfcg.forestry.ubc.ca/resources/cataloguing-in-situ-genetic-resources/about-bec-and-bgc-units/">here</a>.</p></li>
</ul>
<p>These data are collectively used to obtain information on the forests of BC.&nbsp;However, since forests change over time, VRI also includes <u>regular updates</u> of original VRI data to reflect changes in forest composition associated with:</p>
<ul>
<li><p><u>Large-scale</u> <u>natural disturbances</u>:&nbsp;e.g., fires, insects, windthrow, etc.</p></li>
<li><p><u>Human disturbances</u>:&nbsp;e.g., clear-cuts, partial harvests, roads, new urban areas, etc.</p></li>
</ul>
<p>These new openings result in <u>changes to polygon boundaries and attributes relative to prior dates for the same land area</u>.&nbsp; In addition, <u>the attributes of each forested polygon are forecasted for stand-level growth to the current date (labelled as “Projected”)</u>.&nbsp; For example, if the stand age was 50 years in 2000, the updated age (called “Projected Age”) in 2015 is 50+15=65 years. There are some attributes such as species composition that cannot be accurately updated via a forecast.&nbsp; <u>At some point, a re-inventory is needed</u>. Typically, the Province does not regularly update the VRI layers for disturbances on private lands. The VRI for MKRF was actually updated to an entirely new reference year in 2020. We’ve included this data with the course and will introduce it at the end of lab. You can see that the 2014 VRI is largely the same as the 1996 VRI, but when the VRI was updated to a new reference year there were many changes.</p>
<hr>
</section>
<section id="learning-objectives" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="learning-objectives">Learning Objectives</h2>
<ul>
<li><p>Examine differences in the 2014 VRI compared to forest cover layers</p></li>
<li><p>Complete an initial photo-interpretation for forest cover maps using the 2014 VRI standards. Your approach will use a 2D image, but photointerpreters normally use images “stereo-imagery” which combines images to create a 3D representation of the imagery.</p></li>
<li><p>Compare the aerial images to images from Landsat satellites and consider how these might be useful for updated forest land changes.</p></li>
</ul>
<hr>
</section>
<section id="task-1-discover-the-difference-between-forest-cover-and-vri" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="task-1-discover-the-difference-between-forest-cover-and-vri">Task 1: Discover the difference between “Forest Cover” and VRI</h2>
<p>Last week, we used forest cover polygons to look at the forest cover from 1989 and briefly compared changes between 1989 and 1999. These forest cover polygons were created using interpretation of aerial imagery. Both VRI and forest cover polygons intrept components of forests using aerial imagery. However, their standards for photo-interpretation are different.</p>
<p>In our dataset, the forest cover polygons are based on photointepretation of 1987 photos, while the 2014 VRI is based on a 19996 aerial survey. Forest cover polygons are updated for natural and human disturbances, whereas VRI polygons are updated for the same disturbances. VRI polygons are also projected to the updated year. Additionally, VRI includes information on four different forest structure layers, from top canopy to the shrub layer. In this lab, we will work with the top of canopy layer. You can find out more on what attributes are recorded in <a href="https://www2.gov.bc.ca/assets/gov/farming-natural-resources-and-industry/forestry/stewardship/forest-analysis-inventory/data-management/standards/vegcomp_poly_rank1_data_dictionaryv5_2019.pdf">the VRI data dictionary.</a></p>
<section id="building-familiarity-with-vri-data" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="building-familiarity-with-vri-data">Building Familiarity with VRI data</h4>
<p><strong>Step 1:</strong> Open QGIS and save a new map project. Set up this project similarly to how we did in Task 1 lab 1 (INCLUDE REFERENCE HERE).</p>
<p><strong>Step 2:</strong> Add the following layers to your blank map:</p>
<ul>
<li>P_Boundary_MRKF</li>
<li>P_BC_VRI_2014</li>
<li>P_ForestCover_1989</li>
</ul>
<p><strong>Step 3:</strong> Select “P_BC_VRI_2014” and change the layer symbology. Change the outline to “white” ⬜change the fill color to “light grey” and increase the outline stroke width 0.2 mm. Click <strong>Apply and Ok.</strong></p>
<p><strong>Step 4:</strong> Select the “P_ForestCover_1989” and change the symbology. Change the outline color to “orange🟧”</p>
<p><strong>Step 5:</strong> Compare the VRI polygons to the 2006 Orthomosaic. Are there areas where the VRI projection does not make sense? To answer this, set the fill color for the VRI to semi-translucent and zoom to: 1250396, 481902 (*<em>make sure your map CRS is set to BC Conus Albers; EPSG 3005)</em>. You can paste these values into the coordinate box on the bottom of the screen.</p>
<p><img src="images/clipboard-2547981647.png" width="230" height="25"></p>
<p><strong>Step 6:</strong> Load in P_ForestCover_2008. This is the updated forest cover layer as of 2006. Find the name of the forest disturbance that occurred in 2006 at the location identified in <strong>step 5</strong></p>
</section>
<section id="question-1" class="level3" data-number="3.0.1">
<h3 data-number="3.0.1" class="anchored" data-anchor-id="question-1"><span class="header-section-number">3.0.1</span> Question 1:</h3>
<p>Which description of forest composition and structure (VRI and forest cover) has more polygons?</p>
</section>
<section id="question-2" class="level3" data-number="3.0.2">
<h3 data-number="3.0.2" class="anchored" data-anchor-id="question-2"><span class="header-section-number">3.0.2</span> Question 2:</h3>
<p>Which descriptor of forest composition has a larger average polygon? Which one has a larger maximum polygon?</p>
</section>
<section id="question-3" class="level3" data-number="3.0.3">
<h3 data-number="3.0.3" class="anchored" data-anchor-id="question-3"><span class="header-section-number">3.0.3</span> Question 3:</h3>
<p>What is the projected age for the polygon at this site? Does this make sense? Why or why not? Insert a screenshot (include a figure caption!) to support your answer.</p>
</section>
<section id="question-4" class="level3" data-number="3.0.4">
<h3 data-number="3.0.4" class="anchored" data-anchor-id="question-4"><span class="header-section-number">3.0.4</span> Question 4:</h3>
<p>Look for two other forest disturbances or land-cover changes anywhere in MKRF recorded in the 2006 orthomosaic but not recorded in the 2014 VRI.</p>
</section>
<section id="question-5" class="level3" data-number="3.0.5">
<h3 data-number="3.0.5" class="anchored" data-anchor-id="question-5"><span class="header-section-number">3.0.5</span> Question 5:</h3>
<p>Malcom Knapp is privately owned land, meaning not all disturbances are consistently added to VRI. Given this, what are some of the disadvantages of relying on VRI alone? What additional tools can we use to better update VRI? Respond in a clear and well written paragraph format.</p>
<hr>
</section>
</section>
<section id="task-2-segmenting-forest-polygons" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="task-2-segmenting-forest-polygons">Task 2: Segmenting Forest Polygons</h2>
<p>Read through the <a href="https://www2.gov.bc.ca/assets/gov/farming-natural-resources-and-industry/forestry/stewardship/forest-analysis-inventory/forest-cover-inventories/photo-interpretation/standards/vri_photo_interpretation_procedures_version_39.pdf#page=21.84">photo-interpretation standards</a> provided by the Ministry. Note that the linked version is version 5 - reflecting that these standards are fifth version of VRI photo-interpretation standards since 1999 (when the VRI program was established). Focus on <strong>Figure 2.1 and Figure 2.2</strong>. These show initial steps in segmenting the land base into forest cover polygons. You will be interpreting a 2006 photo of area of MKRF using these two figures and “heads-up digitizing.” Normally, this first step would be done using a 3-D view of overlapping aerial images. You will be using a 2-D view for this first step in photo-interpretation to get an idea of how this is initially done. These larger polygons would be further stratified using forest cover attributes, and all attributes added as documented in the VRI photo-interpretation standards.</p>
<p><strong>Step 1</strong> Add the 2008 and the 2006 aerial imagery to your map. Note that the 2008 photo is only part of the MRKF</p>
<p><strong>Step 2</strong> zoom into the three following locations below. Create a <em>formatted</em> table to answer question 6 (@sec-Q6)</p>
<p><strong>Step 3</strong> zoom into a clearcut location in 2008. Think about what characteristics support it is harvested</p>
<section id="sec-Q6" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="sec-Q6">Question 6:</h3>
<p>Zoom into the locations noted on the table. Use the <img src="images/clipboard-1450729439.png" class="img-fluid" width="27"> tool located in the upper right of QGIS to retrieve RGB values for the following areas. Once you have filled in the table, discuss why you think different landcovers have different pixel values.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>NOTE: Remember that for a color rendition of an image, white objects reflect high in all visual bands; green objects reflect higher in the green band; blue objects reflect higher in the blue band; red objects reflect higher in the red band; and black objects have low reflectance in all visual bands.</p>
</div>
</div>
<table class="table">
<caption>Pixel brightness values for different land cover types in MKRF</caption>
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>E</th>
<th>N</th>
<th>Landcover</th>
<th>Red Brightness</th>
<th>Green Brightness</th>
<th>Blue Brightness</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1248400</td>
<td>481890</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>1247760</td>
<td>848198</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>1248195</td>
<td>483318</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>1247019</td>
<td>483138</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
</section>
<section id="question-7" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="question-7">Question 7:</h3>
<p>When you look at a clear cut area, what characteristics support an area is harvested? Consider size, shape, texture, proximity to other features, etc. List three specific characteristics to identify a harvested area that you could give to someone else who has never seen an above view of a clear cut.</p>
</section>
<section id="question-8" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="question-8">Question 8:</h3>
<p>Create a reference table that describes specific characteristics that can help differentiate land cover types using aerial imagery. For each feature in the below table include 3 characteristics of the different land covers.</p>
<table class="table">
<thead>
<tr class="header">
<th>Land cover type</th>
<th>Key Characteristics</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Road</td>
<td></td>
</tr>
<tr class="even">
<td>Partially Harvested Stand</td>
<td></td>
</tr>
<tr class="odd">
<td>Hydro Electrical clearing</td>
<td></td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="task-3-understand-variability-in-pixel-data" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="task-3-understand-variability-in-pixel-data">Task 3: Understand Variability in Pixel Data</h2>
<p>We have established an understanding of the key characteristics of different land cover types and how these relate to brightness values. We will now use QGIS to create a new polygon feature that will help better understand variability in pixel data, and how this variability can help us explore our datasets.</p>
<p><strong>Step 1</strong> Create a new shapefile layer by going to <strong>Layer -&gt; Create a Layer -&gt; Create a new shapefile layer</strong></p>
<p><img src="images/clipboard-477174409.png" class="img-fluid"></p>
<p><strong>Step 2</strong> Save your shapefile to the same location as your exercise two, name this layer “Landcover Types.shp”. For the <strong>Geometry Type</strong> select “polygon.” In the <strong>New Field</strong> window create a <strong>Text</strong> field called “class.” Make sure to click <strong>Add to Fields List.</strong> Click <strong>Ok.</strong> Your new layer should appear in the layers panel.</p>
<p><strong>Step 3</strong> Right click on your new layer in the <strong>layers panel.</strong> Select <strong>Toggle Editing.</strong> The layer can now be actively edited.</p>
<p><strong>Step 4</strong> Click on the polygon tool <img src="images/clipboard-3885190170.png" class="img-fluid"> in the upper left of the screen. This tool allows you to add new polygons to your shapefile. To add a polygon, left-click to begin a shape and add addition vertices. To finish a shape <strong>right-click.</strong> Use this process to add polygons that cover (a) a fresh clearcut (b) a lake (c) an older clearcut (d) a mixed forest (e) coniferous forest in the <u><strong>2006</strong></u> <strong>RGB image</strong>. When you finish a polygon make sure to note the landcover type in your “class” field.</p>
<p><img src="images/clipboard-1460819033.png" class="img-fluid" width="237"></p>
<p><strong>Step 5</strong> once you have finished right-click on your layer in the <strong>Layers</strong> panel to save the layer edits. Additionally, change the <strong>symbology</strong> of this layer to show the individual layer attributes. See an example in <a href="#fig-1">Figure&nbsp;<span>3.1</span></a>.</p>
<div id="fig-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="images/clipboard-1582844239.png" class="img-fluid figure-img" width="552"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;3.1: Landcover types for polygon based on interpretation of 2006 aerial RGB imagery. <em>Note that 2008 is shown in background</em></figcaption><p></p>
</figure>
</div>
<p><strong>Step 5</strong> We will now introduce the <strong>processing toolbox</strong>. This is a great resource for finding tools that help analyze spatial data. The processing toolbox is normally located on the upper right-hand of of the QGIS window. If it is not there, you can load it by going to <strong>View -&gt; Panels -&gt; Processing Toolbox.</strong></p>
<div class="quarto-figure quarto-figure-left">
<figure class="figure">
<p><img src="images/clipboard-3381024759.png" class="img-fluid figure-img" width="470"></p>
</figure>
</div>
<p><strong>Step 6</strong> In the search bar located at the top of the <strong>processing toolbox</strong> type in “Zonal” and select <strong>Zonal statistics.</strong> In the pop-up window make the following selections</p>
<ol type="A">
<li><strong>Input layer:</strong> Select your class polygons</li>
<li><strong>Raster layer</strong>: Select the <strong>2006 RGB</strong> image</li>
<li><strong>Raster band:</strong> Select the green band</li>
<li><strong>Output column prefix:</strong> type “<em>Brt” (for pixel brightness values</em>)</li>
<li><strong>Right click on the “…” in statistics to calculate.</strong> In the new menu select (1) Mean (2) St Dec (2) Minimum and (3) maximum</li>
<li><strong>Save the file to the same location as your exercise 2</strong></li>
</ol>
<p><img src="images/clipboard-1244300705.png" class="img-fluid" width="401"></p>
<p><strong>Step 7</strong> Using the new shapefile, color the shapefile by mean brightness. Under <strong>symbology</strong> select “graduated” and for the color palette choose “greys.” At the top to the color palette window choose <strong>invert color ramp</strong>. Inverting the color ramp means that the polygons where the mean brightness values is low will be closer to black and polygons where the mean brightness is high will be closer to white.</p>
<p><strong>Step 8</strong> We will now create a new map layout to showcase some the forest cover polygons we have created. Go to file <strong>New print layout</strong> andcreate a new map layout named “forest cover polygons.” Make the orientation of new map <strong>horizontal.</strong> Our new map layout will have three different maps. The first, will describe the forest cover polygons we have created. The second, will describe in the mean brightness for the RGB data we have. Finally, we will have a third map that will look at the variability in these brightness responses.</p>
<p><strong>Step 9</strong> We’ll start with the map the describes our forest polygons.</p>
<ol type="A">
<li>change the symbology of the forest polygons shapefile to give each polygon a unique color. Go to symbology -&gt; categorized -&gt; select your “class” field -&gt; and classify. Click <strong>Apply</strong> but NOT <strong>ok.</strong></li>
<li>On the left-hand of this pop-up window go to “labels” and select <strong>Single Label</strong> for <strong>Value</strong> select your “class” field.</li>
<li>Click on <strong>Buffer</strong> and check the box that says <strong>Draw text Buffer</strong> this will put a small white buffer around our labels</li>
<li>Click on <strong>Placement</strong> change the <strong>mode</strong> to <strong>Offset from centroid</strong>. Click the box that says <strong>Allow placing of labels outside of polygons.</strong> Change the <strong>Quadrant</strong> to the upper-left</li>
<li>Click <strong>Apply</strong> - labels should now appear on the map canvas</li>
<li>Click <strong>Ok.</strong></li>
</ol>
<p><img src="images/clipboard-74741472.png" class="img-fluid"></p>
<ol start="7" type="A">
<li>Navigate back to your map layout. Insert a new map for your forest polygons. In the background, include the BC VRI and 2008 RGB image. The screenshot below highlights what should be included. Set the map scale to 70000 to best include all of MKRF.</li>
</ol>
<p><img src="images/clipboard-1857806976.png" class="img-fluid" width="346"></p>
<ol start="8" type="A">
<li><p>In the right-hand side under <strong>Layers</strong> click the checkmark that says <strong>Lock layers and Lock styles for Layers</strong> this prevents your map from automatically updating.</p></li>
<li><p>Add a legend<strong>.</strong> In <strong>Legend items</strong> uncheck “auto update” and remove all legend items are are not your forest cover polygons. On the forest polygon layer right-click to check “hidden.” In the <strong>Title</strong> for the legend put “Forest Polygon Class”</p></li>
<li><p>Right click on the map on your map layout to <strong>copy and paste</strong> the map so there is a duplicate map next to your forest polygon map. With this map selected <strong>uncheck</strong> the <strong>Lock layers and Lock styles for Layers</strong>. Navigate back to your map canvas</p></li>
</ol>
<p><strong>Step 9</strong> We’ll now map the average green brightness value in these polygons.</p>
<ol type="A">
<li>Using your layer that we calculated zonal statistics on, which should still be colored black-to-white. Move this layer to the top of the map canvas.</li>
<li>Navigate back to your map layout. With the copied map selected change the name to “zonal mean.” In the item properties tab click the circular “refresh” button. This will update the map to the current canvas layers. Click <strong>Lock layers and Lock styles for Layer.</strong><br>
<img src="images/clipboard-1003007197.png" class="img-fluid"></li>
<li>Copy the Legend from your polygons layer. Change the reference map to the zonal statistics layer. In the legend properties check “update all”. Change the <strong>Title</strong> to “Mean Bit Brightness (Green Band)”.<br>
<img src="images/clipboard-798660786.png" class="img-fluid"></li>
<li>Right click on the map on your map layout to <strong>copy and paste</strong> the map so there is a duplicate map next to your forest zonal statistics map. With this map selected <strong>uncheck</strong> the <strong>Lock layers and Lock styles for Layers</strong>. Navigate back to your map canvas.</li>
</ol>
<p><strong>Step 10</strong> Follow a similar process to step 9, but this time change the zonal statistics layer to the standard deviation. See <a href="#fig-2">Figure&nbsp;<span>3.2</span></a> for an example of your final output.</p>
<div id="fig-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="images/ForestCoverMap.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;3.2: Example output for forest cover map. **Note your map will be different according to where you place your polygons</figcaption><p></p>
</figure>
</div>
<section id="question-9" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="question-9">Question 9:</h3>
<p>How do values for your different forest polygons layer differ in terms of brightness? What feature had the highest greenness reflectance? Which feature had the most variable greenness reflectance? Use values to support your results.</p>
</section>
<section id="question-10" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="question-10">Question 10:</h3>
<p>Normally, photo-interpreters would have a 3-D view of a stereo-pair of photos and they could see and measure stand heights. What other information might help the photo-interpreter assign heights to each stand?&nbsp; HINTS: As well as imagery, what other information might they access? How do other attributes impact height?</p>
</section>
<section id="map-1" class="level3 unnumbered" style="Color: navy">
<h3 class="unnumbered anchored" style="Color: navy" data-anchor-id="map-1">Map 1:</h3>
<p>Include your map describing your forest polygon layer and the associated brightness values from the 2006 orthophoto.</p>
<hr>
</section>
</section>
<section id="task-4-satellite-images-compared-to-aerial-photographs" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="task-4-satellite-images-compared-to-aerial-photographs">Task 4: Satellite Images Compared to Aerial Photographs</h2>
<p>Images collected using satellites provide the base data used to create Google Maps, Google Earth Views, etc. Of these, data collected on Landsat satellites is very commonly used. However, other imagery is often needed to provide finer spatial details, historic views, and 3-D views. You will learn more about other imagery in FRST 538. For now, you will look at the Landsat imagery provided for MKRF and compare these to the aerial photographs. Specifically, you will look at how these images might be used to update for natural and human disturbances.</p>
<p><strong>Step 1</strong> Add the 2019 Landsat RGB image, keeping both the 2008 and 2006 orthoimages loaded. Clearly, there are differences in the spectral reflectance and the resolution of these two images. However, Landsat is free and is consistently capturing imagery from space every two-weeks (when it is cloud free).</p>
<p><strong>Step 2</strong> qualitatively compare the orthoimages from the satellite data. Use this to answer the last lab questiosn</p>
<p>Which year (1999 or 1989) had a large polygon size for western red-cedar dominated stands? Please answer in hectares.</p>
<section id="question-11" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="question-11">Question 11:</h3>
<p>If you were monitoring a forest area for <u>harvest disturbances</u>, would you choose to get new aerial photographs or would you use available Landsat data? Consider <u>the costs, the spatial resolution of the images relative to the disturbance size, and the frequency that images are acquired</u>.</p>
</section>
<section id="question-12" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="question-12">Question 12:</h3>
<p>What about using landsat data for something like small-scale wind damage? Or small-scale fires? What about roads?</p>
<hr>
</section>
</section>
<section id="lab-questions-deliverables" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="lab-questions-deliverables">Lab Questions &amp; Deliverables</h2>
<ul class="task-list">
<li><p><input type="checkbox">Complete answers to the following questions:</p>
<ul class="task-list">
<li><p><input type="checkbox">Question 1: Which description of forest composition and structure (VRI and forest cover) has more polygons?</p></li>
<li><p><input type="checkbox">Question 2: Which descriptor of forest composition has a larger average polygon? Which one has a larger maximum polygon?</p></li>
<li><p><input type="checkbox">Question 3: What is the projected age for the polygon at this site? Does this make sense? Why or why not? Insert a screenshot (include a figure caption!) to support your answer.</p></li>
<li><p><input type="checkbox">Question 4: Look for two other forest disturbances or land-cover changes anywhere in MKRF recorded in the 2006 orthomosaic but not recorded in the 2014 VR</p></li>
<li><p><input type="checkbox">Question 5: Malcom Knapp is privately owned land, meaning not all disturbances are consistently added to VRI. Given this, what are some of the disadvantages of relying on VRI alone? What additional tools can we use to better update VRI? Respond in a clear and well written paragraph format.</p></li>
<li><p><input type="checkbox">Question 6: Zoom into the locations noted on the table. Use the <img src="images/clipboard-1450729439.png" class="img-fluid" width="27"> tool located in the upper right of QGIS to retrieve RGB values for the following areas. Once you have filled in the table, discuss why you think different landcovers have different pixel values.</p>
<table class="table">
<caption>Pixel brightness values for different land cover types in MKRF</caption>
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>E</th>
<th>N</th>
<th>Landcover</th>
<th>Red Brightness</th>
<th>Green Brightness</th>
<th>Blue Brightness</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1248400</td>
<td>481890</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>1247760</td>
<td>848198</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>1248195</td>
<td>483318</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>1247019</td>
<td>483138</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table></li>
<li><p><input type="checkbox">Question 7: When you look at a clear cut area, what characteristics support an area is harvested? Consider size, shape, texture, proximity to other features, etc. List three specific characteristics to identify a harvested area that you could give to someone else who has never seen an above view of a clear cut.</p></li>
<li><p><input type="checkbox">Question 8: Create a reference table that describes specific characteristics that can help differentiate land cover types using aerial imagery. For each feature in the below table include 3 characteristics of the different land covers.</p></li>
<li><p><input type="checkbox">Question 9: How do values for your different forest polygons layer differ in terms of brightness? What feature had the highest greenness reflectance? Which feature had the most variable greenness reflectance? Use values to support your results.</p></li>
<li><p><input type="checkbox">Question 10: Normally, photo-interpreters would have a 3-D view of a stereo-pair of photos and they could see and measure stand heights. What other information might help the photo-interpreter assign heights to each stand?&nbsp; HINTS: As well as imagery, what other information might they access? How do other attributes impact height?</p></li>
<li><p><input type="checkbox">Question 11: If you were monitoring a forest area for <u>harvest disturbances</u>, would you choose to get new aerial photographs or would you use available Landsat data? Consider <u>the costs, the spatial resolution of the images relative to the disturbance size, and the frequency that images are acquired</u>.</p></li>
<li><p><input type="checkbox">Question 12. What about using landsat data for something like small-scale wind damage? Or small-scale fires? What about roads?</p></li>
</ul></li>
<li><p><input type="checkbox">Complete Maps for :</p>
<ul>
<li><input type="checkbox">Your photo-interpreted forest polygons. Include the mean and standard deviation for the green birghtness values form the 2006 orthomosaic.</li>
<li>Make sure that your map includes:
<ul>
<li>A title</li>
<li>A scale bar</li>
<li>A north arrow</li>
<li>A proper legend</li>
</ul></li>
</ul></li>
</ul>
</section>
<section id="summary" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="summary">Summary</h2>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./01-Introduction to Forestry Datasets in QGIS.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introduction to Forestry Datasets in QGIS</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./Course Data Description.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Data Description for FRST 556 course data</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>